- name: Generic Hunter Tasks
  import_tasks: generic.yml

- name: Login Node Hunter Tasks
  import_tasks: login.yml
  when: "('login' in group_names) or ('master' in group_names)"

- name: Hunter Node Removal Tasks
  import_tasks: remove.yml 
  tags:
    - never
    - remove
