## The name of the cluster
cluster_name: mycluster

## The hostname of the SLURM controller
### Default: The first node in the "login" group, otherwise empty
slurm_server: "{{ groups['login'][0] | default('') }}"

## Node to remove
remove_node:
  - "HOSTNAME_OF_NODE_TO_BE_REMOVED"
  - "HOSTNAME_OF_NODE_TO_BE_REMOVED2"
