- name: Perform Generic Configuration 
  import_tasks: generic.yml

- name: Perform Server Configuration 
  include_tasks: server.yml
  when: "'login' in group_names"
  tags: 
    - update
    - remove
