- name: Set admin access password to provided password
  become: yes
  become_user: grafana
  command: "grafana-cli admin reset-admin-password {{ default_user_password }}" 

- name: Configure server root path (1/2)
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^(.*)root_url =(.*)$'
    line: 'root_url = %(protocol)s://%(domain)s:%(http_port)s/monitor'

- name: Configure server root path (2/2)
  lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: '^(.*)serve_from_sub_path =(.*)$'
    line: 'serve_from_sub_path = true'

- name: Create required directories 
  file:
    path: "{{ item }}"
    state: directory
    owner: grafana
    group: grafana
  loop:
    - /etc/grafana/provisioning/datasources/
    - /etc/grafana/provisioning/dashboards/
    - /var/lib/grafana/dashboards/
  
- name: Configure data source
  copy:
    src: files/prometheus.yaml
    dest: /etc/grafana/provisioning/datasources/prometheus.yaml
    owner: grafana
    group: grafana

- name: Create default dashboard configuration
  copy: 
    src: files/node-exporter-full.yaml
    dest: /etc/grafana/provisioning/dashboards/node-exporter-full.yaml
    mode: '744'
    owner: grafana
    group: grafana

- name: Create default dashboard definition
  copy: 
    src: files/node-exporter-full.json
    dest: /var/lib/grafana/dashboards/node-exporter-full.json
    mode: '744'
    owner: grafana
    group: grafana

- name: Add Hunter nodes to monitoring
  template:
    src: templates/prometheus-hunter.yml
    dest: /opt/flight/opt/prometheus/prometheus.yml
  when: 
    - hunter_hosts |bool
  tags:
    - never
    - update
    - remove

- name: Allow data from nodes in network through firewall
  firewalld:
    zone: public 
    port: '9090/tcp'
    state: enabled
    permanent: yes
    immediate: true

- name: Turn on data server
  service: name=prometheus state=restarted enabled=yes
  tags:
    - update
    - remove

- name: Turn on monitoring server
  service: name=grafana-server state=restarted enabled=yes

- name: Add Monitor WWW Config
  copy:
    src: files/flight-monitor.conf
    dest: /opt/flight/etc/www/server-https.d/monitor.conf

- name: Install Monitor Web-Suite Application 
  copy:
    src: files/flight-monitor.md
    dest: /opt/flight/opt/www/landing-page/default/content/apps/monitor.md

- name: Install Monitor Web-Suite Logo
  copy: 
    src: files/flight-monitor.png
    dest: /opt/flight/opt/www/landing-page/default/content/images/monitor.png
