- name: Perform Server Configuration
  include_tasks: ipaserver.yml
  when: "'ipa' in group_names"
  tags: 
    - update
    - remove

- name: Perform Client Configuration
  include_tasks: ipaclient.yml
  when: 
    - "'ipa' not in group_names"
    - hunter_hosts |bool
  tags:
    - update
    - remove
